### ISSUE TITLE
显示显存4MB，你是怎么解决的？

### ISSUE THREAD

**Issue by isshe** [chengxuray/Hackintosh-thinkpad-e490#1]
我用了10.15.2的镜像，你这个EFI，我开机不了。换回原始的，能开机，但是显存4M，你是如何解决的？

**Comment by isshe** [comment]
能否给个邮箱/QQ，沟通一下？

**Comment by lst** [comment]
留个QQ我联系你，你是e490吗

**Comment by lst** [comment]
https://baijiahao.baidu.com/s?id=1634020958965592465&wfr=spider&for=pc 仿冒一下显卡，我仿冒的是3EA5

**Comment by isshe** [comment]
xxxxxxxxxx

**Comment by isshe** [comment]
我的是e490 i5 8265

**Comment by lst** [comment]
不知道你的真实名字，不能通过验证，可以把我的efi patch里的aml文件删除换成原始的再试试。

**Comment by isshe** [comment]
抱歉抱歉，换一个xxxxxxxx

**Comment by chengxuray** [comment]
问题解决，可以关闭了

**Comment by isshe** [comment]
OK. 感谢大佬。
