### ISSUE TITLE
hevc解码器不可用

### ISSUE THREAD

**Issue by trueboost** [chengxuray/Hackintosh-thinkpad-e490#2]
hevc解码器不可用 老哥能否解决下，要用hevc解码，谢谢了

**Comment by lst** [comment]
能提供一下这个软件吗，顺便具体点儿描述怎么不可用。

**Comment by trueboost** [comment]
> 能提供一下这个软件吗，顺便具体点儿描述怎么不可用。
![QQ20200324-150712](https://user-images.githubusercontent.com/22467274/77397837-50ddbe00-6de1-11ea-8b64-e2d1ae870028.png)

videoproc解码测试不可用

**Comment by trueboost** [comment]
> 能提供一下这个软件吗，顺便具体点儿描述怎么不可用。

还有合上盖子时间太长无法唤醒屏幕 以及唤醒之后音量热键不可用

**Comment by lst** [comment]
打开Clover Configurator，设备设置里边的“属性”
查看是不是有下面这个设置，没有就加上。
AAPL00,override-no-connect
00FFFFFF FFFFFF00 0DAED414 00000000 241A0104 A51F1178 02286597 59548E27 1E505400 00000101 01010101 01010101 01010101 0101B43B 804A7138 3440503C 680035AD 10000018 000000FE 004E3134 30484341 2D454143 0A200000 00FE0043 4D4E0A20 20202020 20202020 000000FE 004E3134 30484341 2D454143 0A200005

**Comment by trueboost** [comment]
> 打开Clover Configurator，设备设置里边的“属性”
> 查看是不是有下面这个设置，没有就加上。
> AAPL00,override-no-connect
> 00FFFFFF FFFFFF00 0DAED414 00000000 241A0104 A51F1178 02286597 59548E27 1E505400 00000101 01010101 01010101 01010101 0101B43B 804A7138 3440503C 680035AD 10000018 000000FE 004E3134 30484341 2D454143 0A200000 00FE0043 4D4E0A20 20202020 20202020 000000FE 004E3134 30484341 2D454143 0A200005

还是一样的结果

**Comment by lst** [comment]
不合盖子，普通的睡眠有问题吗？电源按钮的呼吸灯能正常显示吗？

**Comment by trueboost** [comment]
这个肯定没问题  不合上盖子是没问题的，但有时候会出现无法唤醒的情况  按键有反应 屏幕无法输出，合上盖子小部分时间不能唤醒

lst-roborock <notifications@github.com> 于2020年3月30日周一 下午2:25写道：

**Comment by lst** [comment]
建议用Hackintool 解决一下，在电源选项卡里。我这儿没有这个问题，只能提供一些建议了

**Comment by trueboost** [comment]
HEVC应该没有解决方案了吧

lst-roborock <notifications@github.com> 于2020年3月30日周一 下午2:43写道：

**Comment by lst** [comment]
是的，我翻了一下大佬的文章没找到相关的，尝试了一批其他的platform id，没有有效的。看来帮不上忙了

**Comment by trueboost** [comment]
百度说因为显存也有可能

lst-roborock <notifications@github.com> 于2020年3月30日周一 下午2:55写道：

**Comment by lst** [comment]
我用windows装了videoproc，显示可以解码不能编码。有人说这个和smbios有关系，2016 17才开始有hevc支持，我这个smbios 15,2应该已经是很新的了。

**Comment by trueboost** [comment]
15.2是18年的13寸MBP很新了

lst-roborock <notifications@github.com> 于2020年3月30日周一 下午3:02写道：

**Comment by lst** [comment]
AAPL,ig-platform-id 0900A53E

**Comment by lst** [comment]
device-id A53E0900

**Comment by lst** [comment]
可以试验性的改一下这两个参数，坏处是重启必须重新插hdmi线，好处的能侦测hdmi口的变化。也许对睡眠不能唤醒有用

**Comment by lst** [comment]
AAPL00,override-no-connect 要删除，有这个设置合盖不响应

**Comment by lst** [comment]
现在有了hevc的解决方案，非常简单，升级到最新的clover，如下图方式升级
![image](https://user-images.githubusercontent.com/2010127/79440895-227e8780-8009-11ea-9720-115cc7dbe632.png)

升级Lilu.kext与WhateverGreen.kext到最新版。
![image](https://user-images.githubusercontent.com/2010127/79441072-58bc0700-8009-11ea-9902-8498f76527e5.png)

**Comment by trueboost** [comment]
可以了 谢谢老哥。。。

lst-roborock <notifications@github.com> 于2020年4月16日周四 下午5:40写道：

**Comment by chengxuray** [comment]
问题解决了
