### ISSUE TITLE
还有一个头疼的问题就是插上HDMI接口会不停的切换，无法分屏  

### ISSUE THREAD

**Issue by trueboost** [chengxuray/Hackintosh-thinkpad-e490#3]

**Comment by lst** [comment]
建议找一下显示器的EDID，用hackintool工具检查一下接口，机器之间有差异，黑苹果有时还是得自己动手。

**Comment by lst** [comment]
打开Clover，在机型设置里找到Board-ID
先执行 sudo mount -uw /
再修改/Library/Extensions/AppleGraphicsControl.kext/Contents/PlugIns/AppleGraphicsDevicePolicy.kext/Contents/Info.plist
在ConfigMap里加两行

`<key>Mac-xxx 你的Board-ID</key>`
`<string>none</string>`

最后还得重建缓存才能生效

**Comment by lst** [comment]
删除掉驱动和补丁AppleGraphicsDevicePolicy的设置，删除上面对AppleGraphicsDevicePolicy.kext/Contents/Info.plist的修改并重建缓存
启动参数加上igfxonln=1，参考下面的链接
https://github.com/acidanthera/bugtracker/issues/783

我的设置
`<key>PciRoot(0x0)/Pci(0x2,0x0)</key>
			<dict>
				<key>AAPL,GfxYTile</key>
				<data>AQAAAA==</data>
				<key>AAPL,ig-platform-id</key>
				<data>CQClPg==</data>
				<key>AAPL,slot-name</key>
				<string>Internal@0,2,0</string>
				<key>AAPL01,override-no-connect</key>
				<data>AP///////wAF4wEnj9wAAA4dAQOAPCJ4KoZxo1VTnSUNUFS/7wDRwLMAlQCBgIFAgcABAQEBVl4AoKCgKVAwIDUAVVAhAAAeAAAA/wBHTlhLNEhBMDU2NDYzAAAA/ABRMjdQMUIKICAgICAgAAAA/QAyTB5jHgAKICAgICAgAc8=</data>
				<key>device-id</key>
				<data>pT4AAA==</data>
				<key>device_type</key>
				<string>VGA compatible controller</string>
				<key>disable-external-gpu</key>
				<data>AQAAAA==</data>
				<key>enable-hdmi-dividers-fix</key>
				<data>AQAAAA==</data>
				<key>enable-hdmi20</key>
				<data>AQAAAA==</data>
				<key>enable-lspcon-support</key>
				<data>AQAAAA==</data>
				<key>framebuffer-con0-enable</key>
				<data>AQAAAA==</data>
				<key>framebuffer-con0-pipe</key>
				<data>DAAAAA==</data>
				<key>framebuffer-con1-enable</key>
				<data>AQAAAA==</data>
				<key>framebuffer-con1-has-lspcon</key>
				<data>AQAAAA==</data>
				<key>framebuffer-con1-index</key>
				<data>AQAAAA==</data>
				<key>framebuffer-con1-pipe</key>
				<data>DAAAAA==</data>
				<key>framebuffer-con1-type</key>
				<data>AAgAAA==</data>
				<key>framebuffer-con2-enable</key>
				<data>AQAAAA==</data>
				<key>framebuffer-con2-has-lspcon</key>
				<data>AQAAAA==</data>
				<key>framebuffer-con2-index</key>
				<data>/////w==</data>
				<key>framebuffer-con2-pipe</key>
				<data>DAAAAA==</data>
				<key>framebuffer-con2-type</key>
				<data>AAgAAA==</data>
				<key>framebuffer-fbmem</key>
				<data>AACQAA==</data>
				<key>framebuffer-patch-enable</key>
				<data>AQAAAA==</data>
				<key>framebuffer-stolenmem</key>
				<data>AAAwAQ==</data>
				<key>framebuffer-unifiedmem</key>
				<data>AAAAgA==</data>
				<key>hda-gfx</key>
				<string>onboard-1</string>
				<key>model</key>
				<string>Intel Iris Plus Graphics 655</string>
			</dict>`

**Comment by lst** [comment]
WhateverGreen-1.3.8
Lilu 1.4.3
macos 10.15.4
