### ISSUE TITLE
有没有稍微详细一点的操作替换步骤呢

### ISSUE THREAD

**Issue by guaosi** [chengxuray/Hackintosh-thinkpad-e490#4]
去年折腾过一次，因为hdmi没法使用，后面放弃了。现在看到情况貌似挺不错的，不知道能不能提供一下相关参考的安装教程呢

**Comment by chengxuray** [comment]
首先要先弄到自己的edid，然后复制到如题的位置
设备设置--属性--设备--AAPL01,override-no-connect
![image](https://user-images.githubusercontent.com/59086753/89965400-4b451f80-dc7f-11ea-8690-70225b2b510a.png)

**Comment by xqdxqd** [comment]
您好，请问有遇到S3睡眠唤醒后, Fn快捷键失效，电池状态不更新的问题么

**Comment by chengxuray** [comment]
您好，我没Fn快捷键没有失效的问题，电池状态我遇到的是类似问题。我在S3睡眠唤醒之后，插拔电源之后状态更新不及时了，大概电池电量有1%变化之后才能正常显示。

**Comment by chengxuray** [comment]
可以参考我最新上传的EFI-opencore目录中的14-BATT-TP_Ex80-L43+OWAK.aml 。如果你找到了完美解决方案，希望能发出来一起分享。
