### ISSUE TITLE
用您的OC引导显示不支持的平台

### ISSUE THREAD

**Issue by trueboost** [chengxuray/Hackintosh-thinkpad-e490#5]
![QQ图片20210406230540](https://user-images.githubusercontent.com/22467274/113733229-d900de00-972c-11eb-9199-3d603775dc34.jpg)

**Comment by chengxuray** [comment]
请先做一次清除NVRAM，再重启。
如果不可用，请将config.orig.plist 改名为config.plist 再试一次
