### ISSUE TITLE
无法显示电池电量

### ISSUE THREAD

**Issue by trueboost** [chengxuray/Hackintosh-thinkpad-e490#6]
无法显示电池电量

**Comment by chengxuray** [comment]
<img width="760" alt="image" src="https://user-images.githubusercontent.com/59086753/113805141-8f4ade80-9792-11eb-8a6c-a5091b5fa34b.png">
请加上这几个更名，并且确保加载了SMCBatteryManager.kext

**Comment by lst** [comment]
命令里输入下面的，查看是不是还有ACPI错误。按照错误去搜索事半功倍
log show --last boot | grep -Ei "ACPI Error"

**Comment by trueboost** [comment]
[log.txt](https://github.com/chengxuray/Hackintosh-thinkpad-e490/files/6270258/log.txt)

**Comment by trueboost** [comment]
已经全部启用了   麻烦看下我发得日志    已经正确加载smc电池管理了

**Comment by chengxuray** [comment]
请把这个命令的结果发给我
log show --last boot | grep -Ei "ACPI"

**Comment by chengxuray** [comment]
请问您现在用EFI的是我上传的这个EFI-opencore吗

**Comment by trueboost** [comment]
是的 ，就是您上传的EFI-opencore

**Comment by trueboost** [comment]
我用的是11.2.3  跟系统版本有关系吗？

**Comment by chengxuray** [comment]
没有关系的，我也升级到了11.2.3，机器硬件有差异很正常。电池这块儿问题尤其多，log show --last boot | grep -Ei "ACPI"，把完整的acpi日志发给我看看吧。最好把MaciASL打开，把SYSTEM DTST发给我看看。

**Comment by chengxuray** [comment]
电池补丁建议看一下后边链接里的内容，如果你是双电池的，就要用双电池板的patch。 [thinkpad 电池电量补丁](https://github.com/daliansky/OC-little/tree/1f69dd9b65d4087a3406c59f5629d328ff78ab39/08-%E7%94%B5%E6%B1%A0%E8%A1%A5%E4%B8%81/08-1-Thinkpad)

**Comment by trueboost** [comment]
> 电池补丁建议看一下后边链接里的内容，如果你是双电池的，就要用双电池板的patch。 [thinkpad 电池电量补丁](https://github.com/daliansky/OC-little/tree/1f69dd9b65d4087a3406c59f5629d328ff78ab39/08-%E7%94%B5%E6%B1%A0%E8%A1%A5%E4%B8%81/08-1-Thinkpad)

机型没有任何差异 我也是I5-8265U   16G  2400MHZ     512G固态    机型也是E490

**Comment by chengxuray** [comment]
> > 电池补丁建议看一下后边链接里的内容，如果你是双电池的，就要用双电池板的patch。 [thinkpad 电池电量补丁](https://github.com/daliansky/OC-little/tree/1f69dd9b65d4087a3406c59f5629d328ff78ab39/08-%E7%94%B5%E6%B1%A0%E8%A1%A5%E4%B8%81/08-1-Thinkpad)
> 
> 机型没有任何差异 我也是I5-8265U 16G 2400MHZ 512G固态 机型也是E490

即使是同款机型不同批次也是有微小差异的，我这是8G内存 128G固态的乞丐版E490

**Comment by trueboost** [comment]
> 没有关系的，我也升级到了11.2.3，机器硬件有差异很正常。电池这块儿问题尤其多，log show --last boot | grep -Ei "ACPI"，把完整的acpi日志发给我看看吧。最好把MaciASL打开，把SYSTEM DTST发给我看看。


[System DSDT.zip](https://github.com/chengxuray/Hackintosh-thinkpad-e490/files/6275508/System.DSDT.zip)

**Comment by trueboost** [comment]
已发System DSDT    是.dsl  可以直接看

**Comment by chengxuray** [comment]
我发现了问题，GBIX和GBST没有更名成XBIX和XBST.
注意提前备份然后修改更名
GBIX改成
474249580b 584249580b
GBST改成
474253540c 584253540c

**Comment by trueboost** [comment]
Method那个GBIX？

**Comment by chengxuray** [comment]
> Method那个GBIX？

注意提前备份然后修改更名
GBIX改成
474249580b 584249580b
GBST改成
474253540c 584253540c

**Comment by trueboost** [comment]
> > Method那个GBIX？
> 
> 注意提前备份然后修改更名
> GBIX改成
> 474249580b 584249580b
> GBST改成
> 474253540c 584253540c

Config配置文件么

**Comment by trueboost** [comment]
已解决  谢谢指导

**Comment by Sijiu** [comment]
> > Method那个GBIX？
> 
> 注意提前备份然后修改更名 GBIX改成 474249580b 584249580b GBST改成 474253540c 584253540c

真是厉害呢， 看到这里，E480 Ventura 去改了下电池就出来了👍🏻
